import { describe, expect, it } from 'vitest'
import { chartSeries, lineChartTokens, semanticTokens, visualizationTokens } from '@/theme/tokens'

describe('theme tokens', () => {
  it('defines semantic token groups for the app shell', () => {
    expect(semanticTokens.brand.primary).toBeTruthy()
    expect(semanticTokens.brand.primaryHover).toBeTruthy()
    expect(semanticTokens.brand.primaryActive).toBeTruthy()
    expect(semanticTokens.neutral.background.base).toBeTruthy()
    expect(semanticTokens.neutral.background.subtle).toBeTruthy()
    expect(semanticTokens.neutral.background.muted).toBeTruthy()
    expect(semanticTokens.text.primary).toBeTruthy()
    expect(semanticTokens.text.secondary).toBeTruthy()
    expect(semanticTokens.text.tertiary).toBeTruthy()
    expect(semanticTokens.surface.panel).toBeTruthy()
    expect(semanticTokens.surface.raised).toBeTruthy()
    expect(semanticTokens.surface.overlay).toBeTruthy()
    expect(semanticTokens.surface.strong).toBeTruthy()
    expect(semanticTokens.inverse.surface).toBeTruthy()
    expect(semanticTokens.inverse.surfaceSoft).toBeTruthy()
    expect(semanticTokens.inverse.textPrimary).toBeTruthy()
    expect(semanticTokens.border.default).toBeTruthy()
    expect(semanticTokens.border.strong).toBeTruthy()
    expect(semanticTokens.state.warning.default).toBeTruthy()
    expect(semanticTokens.interactive.focusRing).toBeTruthy()
  })

  it('keeps accent separate from warning semantics', () => {
    expect(semanticTokens.brand.accent).not.toBe(semanticTokens.state.warning.default)
    expect(semanticTokens.brand.accentSoft).not.toBe(semanticTokens.state.warning.soft)
    expect(semanticTokens.brand.accent).not.toBe(semanticTokens.state.danger.default)
  })

  it('defines dedicated visualization aliases for charts and maps', () => {
    expect(visualizationTokens.chart.axis).toBeTruthy()
    expect(visualizationTokens.chart.grid).toBeTruthy()
    expect(visualizationTokens.chart.text).toBeTruthy()
    expect(visualizationTokens.chart.comparison.primary).toBeTruthy()
    expect(visualizationTokens.chart.comparison.secondary).toBeTruthy()
    expect(visualizationTokens.chart.trend.primary.line).toBeTruthy()
    expect(visualizationTokens.chart.trend.secondary.line).toBeTruthy()
    expect(visualizationTokens.chart.statusDistribution).toHaveLength(4)
    expect(visualizationTokens.chart.categorySequential.length).toBeGreaterThanOrEqual(4)
    expect(visualizationTokens.chart.seriesPrimary).toBeTruthy()
    expect(visualizationTokens.chart.seriesWarning).toBeTruthy()
    expect(visualizationTokens.chart.seriesDanger).toBeTruthy()
    expect(visualizationTokens.map.engineering).toBeTruthy()
    expect(visualizationTokens.map.river).toBeTruthy()
    expect(visualizationTokens.map.station).toBeTruthy()
    expect(visualizationTokens.map.warning).toBeTruthy()
    expect(visualizationTokens.map.offline).toBeTruthy()
    expect(visualizationTokens.chart.seriesPrimary).not.toBe(semanticTokens.brand.accent)
    expect(visualizationTokens.chart.seriesWarning).not.toBe(semanticTokens.brand.accent)
    expect(visualizationTokens.map.warning).not.toBe(semanticTokens.brand.accent)
  })

  it('exposes reusable auth tokens for hero, glass card, and inputs', () => {
    expect(semanticTokens.auth.hero.background).toBeTruthy()
    expect(semanticTokens.auth.hero.overlay.strong).toBeTruthy()
    expect(semanticTokens.auth.hero.overlay.medium).toBeTruthy()
    expect(semanticTokens.auth.hero.overlay.soft).toBeTruthy()
    expect(semanticTokens.auth.hero.decorative.badgeBackground).toBeTruthy()
    expect(semanticTokens.auth.hero.decorative.badgeBorder).toBeTruthy()
    expect(semanticTokens.auth.hero.decorative.titleShadow).toBeTruthy()
    expect(semanticTokens.auth.hero.decorative.particle).toBeTruthy()
    expect(semanticTokens.auth.glassCard.background).toBeTruthy()
    expect(semanticTokens.auth.glassCard.shadow).toBeTruthy()
    expect(semanticTokens.auth.input.background).toBeTruthy()
    expect(semanticTokens.auth.input.focusShadow).toBeTruthy()
  })

  it('keeps chart palette keys and line series types available for component consumers', () => {
    expect(chartSeries.alarmLevels.length).toBeGreaterThan(0)
    expect(chartSeries.stationStatus.length).toBeGreaterThan(0)
    expect(chartSeries.comparison.length).toBeGreaterThan(0)
    expect(chartSeries.comparisonSecondary.length).toBeGreaterThan(0)
    expect(chartSeries.statusDistribution.length).toBeGreaterThan(0)
    expect(chartSeries.categorySequential.length).toBeGreaterThan(0)
    expect(lineChartTokens.waterLevel.line).toBeTruthy()
    expect(lineChartTokens.rainfall.line).toBeTruthy()
    expect(lineChartTokens.trendPrimary.line).toBeTruthy()
    expect(lineChartTokens.trendSecondary.line).toBeTruthy()
  })

  it('provides visual effect tokens for gradients, glows, overlays, and shadows', () => {
    expect(semanticTokens.visual.gradient.pageBackground).toBeTruthy()
    expect(semanticTokens.visual.gradient.inverseHero).toBeTruthy()
    expect(semanticTokens.visual.glow.brand).toBeTruthy()
    expect(semanticTokens.visual.glow.brandStrong).toBeTruthy()
    expect(semanticTokens.visual.glow.accentSubtle).toBeTruthy()
    expect(semanticTokens.visual.overlay.decorativeStrong).toBeTruthy()
    expect(semanticTokens.visual.overlay.decorativeMedium).toBeTruthy()
    expect(semanticTokens.visual.overlay.decorativeSoft).toBeTruthy()
    expect(semanticTokens.visual.shadow.emphasis).toBeTruthy()
    expect(semanticTokens.visual.shadow.inverseStrong).toBeTruthy()
  })

  it('keeps usage boundaries clear between brand, accent, warning, and danger', () => {
    expect(semanticTokens.brand.primary).not.toBe(semanticTokens.brand.accent)
    expect(semanticTokens.brand.primary).not.toBe(semanticTokens.state.warning.default)
    expect(semanticTokens.brand.primary).not.toBe(semanticTokens.state.danger.default)
    expect(semanticTokens.state.warning.default).not.toBe(semanticTokens.state.danger.default)
  })
})
